#configuracion de acceso a BD
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update #create-drop #update
  #estrategia de generacion de base de datos
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db_MoneyPlan
    username: postgres
    password: admin

#spring:
#  jpa:
#    database: mysql
#    show-sql: true
#    hibernate:
#      ddl-auto: update
    
#estrategia de generacion de base de datos
#  datasource:
#    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/db_moneyplan?useSSL=false 
#    username: root
#    password: admin
    
server:
  port: 8070 